version: '2'
services:
    web:
        dns: 8.8.8.8
        dns_opt:
          - use-vc
          - no-tld-query
        build:
            context: ./
            dockerfile: deploy/web.docker
        volumes:
            - ./:/var/www
        ports:
            - "8080:80"
        links:
            - app

    app:
        dns: 8.8.8.8
        dns_opt:
          - use-vc
          - no-tld-query
        build:
            context: ./
            dockerfile: deploy/app.docker
        volumes:
            - ./:/var/www